dependencies:
  - name: memcached
    version: 3.2.2
    repository: https://nexus.repo.marketspulse.com/repository/helm/
  - name: tomcat
    version: 0.4.1
    repository: https://nexus.repo.marketspulse.com/repository/helm/
