dependencies:
  - name: minio
    version: 5.0.11
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: memcached
    version: 3.2.2
    repository: https://kubernetes-charts.storage.googleapis.com
