dependencies:
  - name: mariadb
    version: 7.3.12
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: memcached
    version: 3.2.2
    repository: https://kubernetes-charts.storage.googleapis.com
