dependencies:
  - name: mariadb
    version: 7.x.x
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: memcached
    repository: https://kubernetes-charts.storage.googleapis.com
