dependencies:
  - name: tomcat
    version: 0.4.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: memcached
    version: 3.2.2
    repository: https://kubernetes-charts.storage.googleapis.com
