name: Pipeline robokit

on: [push]

robo_kit_deploy:

  needs:
    - build_push_docker
    - create_helm

  runs-on: ubuntu-latest

  steps:
    - name: Robo-Kit Deploy
      run: |
        echo 'Run Robo-Kit Deploy'
